{% set name = "pyDeprecate" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 335742ec53b9d22a0a9ff4f3470300c94935f6e169c74b08aee14d871ca40e00

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - deprecate

about:
  home: https://pypi.org/project/pyDeprecate/
  license: Apache-2.0
  license_file: LICENSE
  summary: Collection of PyTorch native metrics for easy evaluating machine learning models
  description: |
    Simple tooling for marking deprecated functions or classes and re-routing to the new successors' instance.
  dev_url: https://github.com/PyTorchLightning/metrics

extra:
  recipe-maintainers:
    - Borda
